version: '2.2'

services:
    mysql:
        build:
            context: ./mysql
            dockerfile: ./Dockerfile
        ports:
            - 3306:3306
    backend:
        build:
            context: ./backend
            dockerfile: ./Dockerfile
        ports:
            - 3030:3030
        environment:
            - DB_HOST=mysql
    frontend:
        build:
            context: ./frontend
            dockerfile: ./Dockerfile
        ports:
            - 3000:3000
        depends_on:
            - backend
